spring:
  application:
    name: fitQuest

  servlet:
    multipart:
      max-file-size: 10MB
      max-request-size: 10MB



  datasource:
    url: jdbc:postgresql://localhost:5435/fitquest
    driver-class-name: org.postgresql.Driver
    username: fitquest_dev
    password: fitquest_dev12
  jpa:
    generate-ddl: false
    hibernate:
      ddl-auto: none

  flyway:
    enabled: true
    locations: classpath:db/migration

server:
  port: 8080

file:
  upload-dir: uploads