CREATE TABLE character_customization
(
    id              BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    user_id         BIGINT                                  NOT NULL,
    name            VARCHAR(255),
    character_class VARCHAR(255),
    avatar          VARCHAR(255),
    color           VARCHAR(255),
    created_at      TIMESTAMP WITHOUT TIME ZONE,
    updated_at      TIMESTAMP WITHOUT TIME ZONE,
    CONSTRAINT pk_character_customization PRIMARY KEY (id)
);

CREATE TABLE completed_exercises
(
    id                   BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    completed_workout_id BIGINT                                  NOT NULL,
    exercise_id          BIGINT                                  NOT NULL,
    sets_completed       INTEGER                                 NOT NULL,
    reps_completed       INTEGER                                 NOT NULL,
    duration             INTEGER                                 NOT NULL,
    CONSTRAINT pk_completed_exercises PRIMARY KEY (id)
);

CREATE TABLE completed_quests
(
    id               BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    user_id          BIGINT                                  NOT NULL,
    quest_id         BIGINT                                  NOT NULL,
    special_event_id BIGINT                                  NOT NULL,
    completed_at     TIMESTAMP WITHOUT TIME ZONE,
    xp_earned        INTEGER                                 NOT NULL,
    points_earned    INTEGER                                 NOT NULL,
    CONSTRAINT pk_completed_quests PRIMARY KEY (id)
);

CREATE TABLE completed_workouts
(
    id            BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    user_id       BIGINT                                  NOT NULL,
    program_id    BIGINT,
    completed_at  TIMESTAMP WITHOUT TIME ZONE,
    xp_earned     INTEGER                                 NOT NULL,
    points_earned INTEGER                                 NOT NULL,
    CONSTRAINT pk_completed_workouts PRIMARY KEY (id)
);

CREATE TABLE exercises
(
    id               BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    api_id           VARCHAR(255),
    name             VARCHAR(255),
    category         VARCHAR(255),
    difficulty       VARCHAR(255),
    calories_per_min INTEGER                                 NOT NULL,
    xp_per_min       INTEGER                                 NOT NULL,
    equipment        VARCHAR(255),
    description      VARCHAR(255),
    created_by_user  BOOLEAN                                 NOT NULL,
    created_at       TIMESTAMP WITHOUT TIME ZONE,
    updated_at       TIMESTAMP WITHOUT TIME ZONE,
    CONSTRAINT pk_exercises PRIMARY KEY (id)
);

CREATE TABLE program_exercises
(
    id          BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    program_id  BIGINT                                  NOT NULL,
    exercise_id BIGINT                                  NOT NULL,
    order_index INTEGER                                 NOT NULL,
    sets        INTEGER                                 NOT NULL,
    reps        INTEGER                                 NOT NULL,
    duration    INTEGER                                 NOT NULL,
    CONSTRAINT pk_program_exercises PRIMARY KEY (id)
);

CREATE TABLE quests
(
    id            BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    name          VARCHAR(255),
    description   VARCHAR(255),
    xp_reward     INTEGER                                 NOT NULL,
    points_reward INTEGER                                 NOT NULL,
    difficulty    VARCHAR(255),
    category      VARCHAR(255),
    duration      INTEGER                                 NOT NULL,
    icon          VARCHAR(255),
    is_custom     BOOLEAN                                 NOT NULL,
    created_at    TIMESTAMP WITHOUT TIME ZONE,
    updated_at    TIMESTAMP WITHOUT TIME ZONE,
    CONSTRAINT pk_quests PRIMARY KEY (id)
);

CREATE TABLE rewards
(
    id          BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    user_id     BIGINT                                  NOT NULL,
    name        VARCHAR(255),
    description VARCHAR(255),
    icon        VARCHAR(255),
    requirement VARCHAR(255),
    rarity      TIMESTAMP without time zone,
    unlocked    BOOLEAN                                 NOT NULL,
    created_at  TIMESTAMP WITHOUT TIME ZONE,
    updated_at  TIMESTAMP WITHOUT TIME ZONE,
    CONSTRAINT pk_rewards PRIMARY KEY (id)
);

CREATE TABLE special_events
(
    id                BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    name              VARCHAR(255),
    description       VARCHAR(255),
    theme             VARCHAR(255),
    start_date        date,
    end_date          date,
    xp_multiplier     DOUBLE PRECISION                        NOT NULL,
    points_multiplier DOUBLE PRECISION                        NOT NULL,
    special_reward    VARCHAR(255),
    active            BOOLEAN                                 NOT NULL,
    icon              VARCHAR(255),
    created_at        TIMESTAMP WITHOUT TIME ZONE,
    updated_at        TIMESTAMP WITHOUT TIME ZONE,
    CONSTRAINT pk_special_events PRIMARY KEY (id)
);

CREATE TABLE user_special_events
(
    id               BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    user_id          BIGINT                                  NOT NULL,
    special_event_id BIGINT                                  NOT NULL,
    joined_at        TIMESTAMP WITHOUT TIME ZONE,
    CONSTRAINT pk_user_special_events PRIMARY KEY (id)
);

CREATE TABLE user_weekly_challenges
(
    id                  BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    user_id             BIGINT                                  NOT NULL,
    weekly_challenge_id BIGINT                                  NOT NULL,
    current_progress    INTEGER                                 NOT NULL,
    completed           BOOLEAN                                 NOT NULL,
    created_at          TIMESTAMP WITHOUT TIME ZONE,
    updated_at          TIMESTAMP WITHOUT TIME ZONE,
    CONSTRAINT pk_user_weekly_challenges PRIMARY KEY (id)
);

CREATE TABLE users
(
    id               BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    username         VARCHAR(255)                            NOT NULL,
    email            VARCHAR(255)                            NOT NULL,
    password         VARCHAR(255)                            NOT NULL,
    level            INTEGER                                 NOT NULL,
    current_xp       INTEGER                                 NOT NULL,
    xp_to_next_level INTEGER                                 NOT NULL,
    strength         INTEGER                                 NOT NULL,
    endurance        INTEGER                                 NOT NULL,
    agility          INTEGER                                 NOT NULL,
    total_points     INTEGER                                 NOT NULL,
    created_at       TIMESTAMP WITHOUT TIME ZONE,
    updated_at       TIMESTAMP WITHOUT TIME ZONE,
    CONSTRAINT pk_users PRIMARY KEY (id)
);

CREATE TABLE weekly_challenges
(
    id            BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    name          VARCHAR(255),
    description   VARCHAR(255),
    target        INTEGER                                 NOT NULL,
    xp_reward     INTEGER                                 NOT NULL,
    points_reward INTEGER                                 NOT NULL,
    category      VARCHAR(255),
    start_date    date,
    end_date      date,
    active        BOOLEAN                                 NOT NULL,
    icon          VARCHAR(255),
    created_at    TIMESTAMP WITHOUT TIME ZONE,
    updated_at    TIMESTAMP WITHOUT TIME ZONE,
    CONSTRAINT pk_weekly_challenges PRIMARY KEY (id)
);

CREATE TABLE workout_programs
(
    id                 BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    user_id            BIGINT,
    name               VARCHAR(255),
    description        VARCHAR(255),
    total_duration     INTEGER                                 NOT NULL,
    estimated_calories INTEGER                                 NOT NULL,
    estimated_xp       INTEGER                                 NOT NULL,
    created_at         TIMESTAMP WITHOUT TIME ZONE,
    updated_at         TIMESTAMP WITHOUT TIME ZONE,
    CONSTRAINT pk_workout_programs PRIMARY KEY (id)
);

ALTER TABLE character_customization
    ADD CONSTRAINT uc_character_customization_user UNIQUE (user_id);

ALTER TABLE users
    ADD CONSTRAINT uc_users_email UNIQUE (email);

ALTER TABLE users
    ADD CONSTRAINT uc_users_username UNIQUE (username);

ALTER TABLE character_customization
    ADD CONSTRAINT FK_CHARACTER_CUSTOMIZATION_ON_USER FOREIGN KEY (user_id) REFERENCES users (id);

ALTER TABLE completed_exercises
    ADD CONSTRAINT FK_COMPLETED_EXERCISES_ON_COMPLETED_WORKOUT FOREIGN KEY (completed_workout_id) REFERENCES completed_workouts (id);

ALTER TABLE completed_exercises
    ADD CONSTRAINT FK_COMPLETED_EXERCISES_ON_EXERCISE FOREIGN KEY (exercise_id) REFERENCES exercises (id);

ALTER TABLE completed_quests
    ADD CONSTRAINT FK_COMPLETED_QUESTS_ON_QUEST FOREIGN KEY (quest_id) REFERENCES quests (id);

ALTER TABLE completed_quests
    ADD CONSTRAINT FK_COMPLETED_QUESTS_ON_SPECIAL_EVENT FOREIGN KEY (special_event_id) REFERENCES special_events (id);

ALTER TABLE completed_quests
    ADD CONSTRAINT FK_COMPLETED_QUESTS_ON_USER FOREIGN KEY (user_id) REFERENCES users (id);

ALTER TABLE completed_workouts
    ADD CONSTRAINT FK_COMPLETED_WORKOUTS_ON_PROGRAM FOREIGN KEY (program_id) REFERENCES workout_programs (id);

ALTER TABLE completed_workouts
    ADD CONSTRAINT FK_COMPLETED_WORKOUTS_ON_USER FOREIGN KEY (user_id) REFERENCES users (id);

ALTER TABLE program_exercises
    ADD CONSTRAINT FK_PROGRAM_EXERCISES_ON_EXERCISE FOREIGN KEY (exercise_id) REFERENCES exercises (id);

ALTER TABLE program_exercises
    ADD CONSTRAINT FK_PROGRAM_EXERCISES_ON_PROGRAM FOREIGN KEY (program_id) REFERENCES workout_programs (id);

ALTER TABLE rewards
    ADD CONSTRAINT FK_REWARDS_ON_USER FOREIGN KEY (user_id) REFERENCES users (id);

ALTER TABLE user_special_events
    ADD CONSTRAINT FK_USER_SPECIAL_EVENTS_ON_SPECIAL_EVENT FOREIGN KEY (special_event_id) REFERENCES special_events (id);

ALTER TABLE user_special_events
    ADD CONSTRAINT FK_USER_SPECIAL_EVENTS_ON_USER FOREIGN KEY (user_id) REFERENCES users (id);

ALTER TABLE user_weekly_challenges
    ADD CONSTRAINT FK_USER_WEEKLY_CHALLENGES_ON_USER FOREIGN KEY (user_id) REFERENCES users (id);

ALTER TABLE user_weekly_challenges
    ADD CONSTRAINT FK_USER_WEEKLY_CHALLENGES_ON_WEEKLY_CHALLENGE FOREIGN KEY (weekly_challenge_id) REFERENCES weekly_challenges (id);

ALTER TABLE workout_programs
    ADD CONSTRAINT FK_WORKOUT_PROGRAMS_ON_USER FOREIGN KEY (user_id) REFERENCES users (id);